baseURL: https://blogs.benro.tech/
languageCode: en-us
title: Benro's Blogs
theme: PaperMod

googleAnalytics: G-DL7393DNJM
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

params:
  env: production
  images: ["hem.png"]
  homeInfoParams:
      Title: Welcome to Benro's Blogs 👋
      Content: I am Hemanth Krishna, a CS Undergrad. This is the place where i write about various tehc
  socialIcons:
      - name: "GitHub"
        url: "https://github.com/DarthBenro008"
      - name: "twitter"
        url: "https://twitter.com/hemanth_kri"
      - name: "email"
        url: "mailto://hkpdev008@gmail.com"
      - name: "LinkedIn"
        url: "https://www.linkedin.com/in/darthbenro008/"
      - name: "rss"
        url: "index.xml"

  author: ["Hemanth Krishna"]
  ShowShareButtons: true
  ShowReadingTime: true
  ShowToc: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  comments: true
  editPost:
        URL: "https://github.com/darthbenro008/benro-blogs/content"
        Text: "Suggest Changes"
        appendFilePath: true
  assets:
        disableHLJS: true
menu:
    main:
        - identifier: search
          name: Search
          url: /search/
          weight: 10
        - identifier: archives
          name: Archive
          url: /archives/
          weight: 20
        - identifier: categories
          name: Series
          url: /categories/
          weight: 30
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 40
        - identifier: about
          name: About
          url: /about/
          weight: 50
outputs:
    home:
        - HTML
        - RSS
        - JSON 
markup:
    goldmark:
      renderer:
        unsafe: true
    highlight:
        codeFences: true
        guessSyntax: true
        lineNos: false
        style: monokai